routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('user','UsersController');

Route::get('delete/{id}', ['as' => 'user.delete', 'uses' => 'UsersController@destroy']);
Route::post('update/{id}', ['as' => 'user.update', 'uses' => 'UsersController@update']);

app/Career.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Career extends Model
{
    protected $fillable = [
        'name', 'career_id'
    ];

      /**
     * Get the user that owns the career.
     */
    public function user()
    {
        return $this->hasMany('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'age',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

     /**
     * Get the career record associated with the user.
     */
    public function career()
    {
        return $this->belongsTo('App\Career');
    }

    /**
     * Save data from user
     */
    public static function saveData($request)
    {
        $user = new User;

        $user->name      = $request->name;
        $user->email     = $request->email;
        $user->age       = $request->age;
        $user->career_id = $request->career_id;
        $user->save();

        return $user;
    }

    /**
     * Update data from user
     */
    public static function updateData($request, $id)
    {
        $user = User::findOrfail($id);

        $user->name      = $request->name;
        $user->email     = $request->email;
        $user->age       = $request->age;
        $user->career_id = $request->career_id;
        $user->save();

        return $user;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;

use App\Career;
use App\User;

use Redirect;
use Session;
class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.list',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $careers = Career::all();
        return view('users.create',compact('careers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = User::saveData($request);

        if($user) {
            Session::flash('message','Se guardo correctamente :)');
            return Redirect::to('/user');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrfail($id);

        return view('users.read',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrfail($id);
        $careers = Career::all();

        return view('users.edit',compact('user','careers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        $user = User::updateData($request, $id);
        $careers = Career::all();

        if($user) {
            Session::flash('message','Se actualizo correctamente :)');
            return view('users.edit',compact('user','careers'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = User::findOrfail($id);
        $users = User::all();

        $delete->delete();

        if($delete) {
            Session::flash('message','Has eliminado un registro :(');
            return redirect('/user')->with('users');
        }
    }
}

resources/views/alerts/error.blade.php
@if(count($errors)>0)
    @foreach($errors->all() as $error)
		<div class="alert alert-danger" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
			{!! $error !!}
		</div>
    @endforeach
@endif

resources/views/alerts/success.blade.php
@if(Session::has('message'))
	<div class="alert alert-success" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
            </button>
		{{Session::get('message')}}
    </div>
@endif

resources/views/alerts/warning.blade.php
@if(Session::has('warning'))
	<div class="alert alert-warning" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
            </button>
		{{Session::get('warning')}}
    </div>
@endif

resources/views/home.blade.php
@extends('layout.master')

@section('content')

  <div class="w-50 mx-auto pt-5 align-middle col-center">
    <h1 class=" pb-5 text-center display-4">Laravel desde cero</h1>

    <div class="row text-center pt-5 ">
      <div class="col-sm  center-block">
        <p><a href="https://laravel.com/" class="text-info">Laravel</a></p>
      </div>
      <div class="col-sm">
        <p><a href="http://getbootstrap.com/" class="text-info">Bootstrap</a></p>
      </div>
      <div class="col-sm">
        <p><a href="https://goo.gl/CLZ3pA" class="text-info">Curso</a></p>
      </div>
      <div class="col-sm">
        <p><a href="#" class="text-info">@xochescam</a></p>
      </div>
    </div>
  </div>

@endsection

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html>

  <title>Laravel desde cero</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="cleartype" content="on">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

  <body>
    @include('partials.navbar')

    <div class="container">
        @yield('content')
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>

</html>

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <a class="navbar-brand" href="{{ url('/') }}">Laravel desde cero</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{{ url('/user') }}">Lista de usuarios</a>
      <a class="nav-item nav-link" href="{{ url('/user/create') }}">Crear usuario</a>
    </div>
  </div>
</nav>

resources/views/users/create.blade.php
@extends('layout.master')

@section('content')

  <h2 class="p-t text-center">Crear usuario</h2>
  <hr class="mb-5">

  @include('alerts.error')
  @include('alerts.success')
  @include('alerts.warning')

  <div class="card w-75 bg-light mx-auto">
    <div class="card-body">
      <form method="POST" action="{{ url('/user') }}">
        @include('users.form')
      </form>
    </div>
  </div>

@endsection

resources/views/users/edit.blade.php
@extends('layout.master')

@section('content')

  <h2 class="p-t text-center">Editar</h2>
  <hr class="mb-5">

  @include('alerts.error')
  @include('alerts.success')
  @include('alerts.warning')

  <div class="card w-75 bg-light mx-auto">
    <div class="card-body">
      <form method="POST" action="{{ route('user.update',$user->id) }}">
        @include('users.form')
      </form>
    </div>
  </div>

@endsection

resources/views/users/form.blade.php
<input name="_token" type="hidden" value="{{ csrf_token() }}">

<div class="form-group row">
  <label for="name" class="col-sm-2 col-form-label">Nombre:</label>
  <div class="col-sm-10">
    <input type="text" name="name" class="form-control" id="name" placeholder="Nombre" value="{{ isset($user->name) ? $user->name : old('name') }}">
  </div>
</div>

<div class="form-group row">
  <label for="email" class="col-sm-2 col-form-label">E-mail:</label>
  <div class="col-sm-10">
    <input type="email" name="email" class="form-control" id="email" placeholder="ejemplo@email.com" value="{{ isset($user->email) ? $user->email : old('email') }} ">
  </div>
</div>

<div class="form-group row">
  <label for="age" class="col-sm-2 col-form-label">Edad:</label>
  <div class="col-sm-10">
    <input type="number" name="age" class="form-control" id="age" value="{{ isset($user->age) ? $user->age : old('age') }}">
  </div>
</div>

<div class="form-group row">
  <label for="career_id" class="col-sm-2 col-form-label">Carrera:</label>
  <div class="col-sm-10">
    <select class="form-control" name="career_id" id="career_id">
      <option value="">Seleccionar</option>
      @foreach($careers as $career)

        @if( (isset($user->age) && $user->career_id == $career->id) || (old('age') == $career->id) )
          <option value="{{ $career->id }}" selected>{{ $career->name }}</option>
        @else
          <option value="{{ $career->id }}">{{ $career->name }}</option>
        @endif

      @endforeach
    </select>
  </div>
</div>

<div class="form-group row">
  <div class="offset-sm-2 col-sm-10">
    <button type="submit" class="btn btn-primary">Guardar</button>
  </div>
</div>

resources/views/users/list.blade.php
@extends('layout.master')

@section('content')

  <h2 class="p-t text-center">Lista de usuarios</h2>
  <hr class="mb-5">

  @include('alerts.success')

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Correo</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      @foreach($users as $user)
        <tr>
          <th>{{ $user->name }}</th>
          <td>{{ $user->email }}</td>
          <td class="text-center">
            <a href="{{ route('user.show',$user->id) }}" class="btn btn-success " role="button" aria-pressed="true" >Ver</a>
            <a href="{{ route('user.edit',$user->id) }}" class="btn btn-info" role="button" aria-pressed="true">Editar</a>
            <a href="{{ route('user.delete', $user->id) }}" class="btn btn-danger" role="button" aria-pressed="true">Eliminar</a>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>

@endsection

resources/views/users/read.blade.php
@extends('layout.master')

@section('content')

  <h2 class="p-t text-center">Ver usuario</h2>
  <hr class="mb-5">

  <div class="card w-50 bg-light mx-auto">
    <div class="card-body">
      <p class="font-weight-bold">Nombre:</p>
      <p class="card-text">{{ $user->name }}</p>

      <p class="font-weight-bold">Email:</p>
      <p class="card-text">{{ $user->email }}</p>

      <p class="font-weight-bold">Edad:</p>
      <p class="card-text">{{ $user->age }}</p>

      <p class="font-weight-bold">Carrera:</p>
      <p class="card-text">{{ $user->career->name }}</p>
    </div>
  </div>

@endsection